spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath*:mapper/*.xml  # 扫描resources下mapper中的xml文件

